env:
  - CXX=g++-4.8 TRAVIS=true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
  - redis-server

cache:
  directories:
    - node_modules

sudo: false
language: node_js
node_js:
  - "7"
  - "8"
script:
  - npm test
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
